server:
  port: 9090

spring:
  application:
    name: showman

  datasource:
    url: jdbc:postgresql://localhost:5432/showmandb
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
